# Generated by Django 5.2.1 on 2025-05-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('class_name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('grade', models.CharField()),
            ],
        ),
    ]
